openapi: 3.0.0
info:
  title: IAM Device API
  version: 1.0.0
paths:
  /devices:
    post:
      summary: Create Device
      description: |  
        This endpoint is used to create a new device within a specific account. Each device must have a unique combination of serial number, model, and manufacturer. Optionally, the device can be associated with one or more groups.
      
        **Note:** Changes in the specification are anticipated for the following reasons
        - *The definition of groups and their association with devices is being refined*
        - *The definition of the model is being improved to enhance data integrity*
      
      parameters:
        - name: accountId
          in: query
          required: false
          description: Unique Identifier of an account.
          schema:
            type: string
            format: uuid
        - name: groupId
          in: query
          description: Unique Identifier of a group.
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        description: Object containing details about the device to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceCreateRequest'
      responses:
        '201':
          description: Device successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceResponse'
      tags:
        - Device
    get:
      tags:
        - Device
      summary: List Devices
      description: This endpoint retrieves a list of all devices that belong to an account. Clients can use this endpoint to search and paginate through devices. It supports optional query parameters to filter results based on search queries, account identifiers, and pagination settings. 
      parameters:
        - name: q
          in: query
          required: false
          description: Query string for searching devices.
          schema:
            type: string
        - name: accountId
          in: query
          required: false
          description: Unique Identifier of an account.
          schema:
            type: string
            format: uuid
        - name: pageSize
          in: query
          required: false
          description: Number of devices to return per page.
          schema:
            type: integer
      responses:
        '200':
          description: Successful response with a list of devices.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceListResponse'
  /devices/{deviceId}:
    patch:
      tags:
        - Device
      summary: Update Device
      description: |
        This endpoint allows updating the details of an existing device. The device is identified by its unique identifier provided in the path parameter. The request body must include the updated details of the device. It is useful for modifying device attributes such as model, manufacturer, firmware, and description.
        
        **Note:** Changes in the specification are anticipated for the following reason
        - *The definition of the model is being improved to enhance data integrity*
      parameters:
        - name: deviceId
          in: path
          required: true
          description: Unique identifier of the device to be updated.
          schema:
            type: string
      requestBody:
        required: true
        description: Object containing the updated details of the device.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceUpdateRequest'
      responses:
        '200':
          description: Device successfully updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceResponse'
    get:
      tags:
        - Device
      summary: Get Device
      description: This endpoint retrieves the detailed information of a specific device identified by its unique identifier provided in the path parameter. This is useful for obtaining the complete details of a device, including its serial number, model, manufacturer, firmware, description, and metadata such as create and update timestamps.
      parameters:
        - name: deviceId
          in: path
          required: true
          description: Unique identifier of the device to be retrieved.
          schema:
            type: string
      responses:
        '200':
          description: Successful response with the device details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceResponse'
    delete:
      tags:
        - Device
      summary: Delete Device
      description: This endpoint deletes a specific device identified by its unique identifier provided in the path parameter. This is useful for removing devices that are no longer needed or being decommissioned. Once deleted, the device's data will be permanently removed from the system and will not be retrievable.
      parameters:
        - name: deviceId
          in: path
          required: true
          description: Unique identifier of the device to be deleted.
          schema:
            type: string
      responses:
        '204':
          description: Device successfully deleted.
  /devices/{deviceId}/groups:
    get:
      tags:
        - Group Association
      summary: Get Groups associated with Device
      description: This endpoint retrieves the list of groups associated with a specific device identified by its unique identifier provided in the path parameter. It is useful for understanding the associations between devices and groups within the system.
      parameters:
        - name: deviceId
          in: path
          required: true
          description: Unique identifier of the device.
          schema:
            type: string
      responses:
        '200':
          description: Successful response with the list of associated groups.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupListResponse'
  /devices/{deviceId}/certificates:
    post:
      tags:
        - Certificate Association
      summary: Associate Device with Certificate
      description: |
        This endpoint creates and associates a certificate with a specific device identified by its unique identifier provided in the path parameter. The request body must include the details of the certificate to be created and associated with the device. This is useful for securely managing device authentication and ensuring that devices can establish trusted connections. 
        
        There are three ways to create a certificate:
          - Cloud Core CA
          - External Certificate
          - Certificate Signing Request (CSR)
          
        **Note :** 
         Each device can be hold upto a maximum of 5 certificates.
        
      parameters:
        - name: deviceId
          in: path
          required: true
          description: Unique identifier of the device.
          schema:
            type: string
      requestBody:
        required: true
        description: Object containing the details of the certificate to be associated with the device.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificateAssociationRequest'
            examples:
              "Cloud Core Certificate":
                description: Use certCommonName to generate a certificate from the Cloud Core Certificate Authority
                value:
                  certCommonName: "string"
              "Certificate Signing Request":
                description:  Provide a Certificate Signing Request to generate a certificate.
                value:
                  csr: "string"
              "External Certificate":
                description : Provide an existing public certificate and CA certificate origin.
                value:
                  publicCert: "string"
                  caCertOrigin: "string"
      responses:
        '201':
          description: Certificate successfully associated with the device.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateResponse'
    get:
      tags:
        - Certificate Association
      summary: Get Certificates associated with Device
      description: This endpoint retrieves the certificates associated with a specific device identified by its unique identifier provided in the path parameter. This is useful for viewing and managing the certificates that have been issued to a device, ensuring that you can keep track of the certificate's details.
      parameters:
        - name: deviceId
          in: path
          required: true
          description: Unique identifier of the device.
          schema:
            type: string
      responses:
        '200':
          description: Successful response with the list of associated certificates.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateListResponse'
  /devices/{deviceId}/certificates/{certificateId}:
    delete:
      tags:
        - Certificate Association
      summary: Delete Certificate
      description: This endpoint removes the association of a device with a specific certificate and deletes the certificate identified by its unique identifier provided in the path parameter. This is useful for deleting certificates that are no longer needed or have been compromised, ensuring that only valid and necessary certificates are associated with a device.
      parameters:
        - name: deviceId
          in: path
          required: true
          description: Unique identifier of the device.
          schema:
            type: string
            format: uuid
        - name: certificateId
          in: path
          required: true
          description: Unique identifier of the certificate.
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Certificate successfully deleted.
components:
  schemas:
    DeviceCreateRequest:
      type: object
      properties:
        serialNumber:
          type: string
          description: Device Serial Number.
        model:
          type: string
          description: Model to which the device belongs.
        manufacturer:
          type: string
          description: Manufacturer associated with the device.
        firmware:
          type: string
          description: Firmware details of the device.
        description:
          type: string
          description: Short note about device details.
    DeviceUpdateRequest:
      type: object
      properties:
        model:
          type: string
          description: Model to which the device belongs.
        manufacturer:
          type: string
          description: Manufacturer associated with the device.
        firmware:
          type: string
          description: Firmware details of the device.
        description:
          type: string
          description: Short note about device details.
    DeviceResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the device.
        serialNumber:
          type: string
          description: Device Serial Number.
        model:
          type: string
          description: Model to which the device belongs.
        manufacturer:
          type: string
          description: Manufacturer associated with the device.
        firmware:
          type: string
          description: Firmware details of the device.
        description:
          type: string
          description: Short note about device details.
        metadata:
          type: object
          properties:
            createdBy:
              type: string
              description: Identifier of the subject who created the device.
            createdAt:
              type: string
              format: date-time
              description: Timestamp when the device was created.
            updatedBy:
              type: string
              description: Identifier of the subject who last updated the device.
            updatedAt:
              type: string
              format: date-time
              description: Timestamp when the device was last updated.
    DeviceListResponse:
      type: object
      properties:
        links:
          type: object
          properties:
            prev:
              type: string
              description: Link to the previous page of results.
            first:
              type: string
              description: Link to the first page of results.
            next:
              type: string
              description: Link to the next page of results.
            self:
              type: string
              description: Link to the current page of results.
        items:
          type: array
          items:
            $ref: '#/components/schemas/DeviceResponse'
    GroupListResponse:
      type: object
      properties:
        links:
          type: object
          properties:
            prev:
              type: string
              description: Link to the previous page of results.
            first:
              type: string
              description: Link to the first page of results.
            next:
              type: string
              description: Link to the next page of results.
            self:
              type: string
              description: Link to the current page of results.
        items:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                description: Unique identifier of the group.
              name:
                type: string
                description: Name of the group.
              metadata:
                type: object
                properties:
                  createdBy:
                    type: string
                    description: Identifier of the subject who created the group.
                  createdAt:
                    type: string
                    format: date-time
                    description: Timestamp when the group was created.
                  updatedBy:
                    type: string
                    description: Identifier of the subject who last updated the group.
                  updatedAt:
                    type: string
                    format: date-time
                    description: Timestamp when the group was last updated.
    CertificateAssociationRequest:
      type: object
      properties:
        certCommonName:
          type: string
          description: Common name of the certificate.
        csr:
          type: string
          description: Certificate Signing Request (CSR).
        caCertOrigin:
          type: string
          description: Origin of the Certificate Authority (CA) certificate.
        publicCert:
          type: string
          description: Public certificate.
    CertificateResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the certificate.
        certificate:
          type: string
          description: Certificate details.
        name:
          type: string
          description: Name of the certificate.
        expiryAtDateTime:
          type: string
          format: date-time
          description: Expiry date and time of the certificate.
        thumbprint:
          type: string
          description: Thumbprint of the certificate.
        metadata:
          type: object
          properties:
            createdBy:
              type: string
              description: Identifier of the subject who created the certificate.
            createdAt:
              type: string
              format: date-time
              description: Timestamp when the certificate was created.
    CertificateListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CertificateResponse'